SELECT TABLE_NAME, ROW_COUNT from practice_data.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='TPCH_SF10' and TABLE_TYPE='BASE TABLE';

SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT from practice_data.INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG='PRACTICE_DATA' and TABLE_TYPE='BASE TABLE';